# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Test

on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
